[package]
name = "cav-synth"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.20.1"
iced = { version = "0.13", features = ["tokio"] }
tokio = { version = "1", features = ["rt"] }
midir = "0.10.1"
